### PR TITLE
4 feature 6 workout data analysis

### PR DESCRIPTION
**Pull request by tejcapildeo**
Entities and partial code for graph use case.

### CODE REVIEW

**Review by TimmyTurner691 — DISMISSED** [review]
The code is kept clean, all model and view classes are kept separate from each other and the controller and presenter classes handle the interaction between the two as it's supposed to. Entity classes are also entirely independent of any type higher up in the hierarchy as they should be.

**Review by absolute-xero7 — COMMENTED** [review]
Everything looks good to me, clean architecture is being followed, no code smells that I can see.

**Review by bdls-jamal — DISMISSED** [review]
Coding Style: 
- Classes are named consistently
- Methods are named consistently
- Some deadspace inbetween lines in functions/between the end of a function and its '}' can be omitted
- code is readible
- Looks good to me!

**Comment by tejcapildeo** [comment]
Merging without review. Review will be done in the future.

**Review by ghost — COMMENTED** [review]
Java docs are very clear, really like how for each class java doc is provided to describe the function of the class, makes it very easy for other team members to understand what a particular class does in the big picture.

**Pull request merged**
