### PR TITLE
1.0 feature 2 dashboard settings pull request

### LINKED ISSUE #1: [Feature 2] <dashboard settings>
Navigation system + settings page to access various user settings that can be interacted with.

### PR DESCRIPTION
**Pull request by bdls-jamal**
**ACTION REQUIRED:** Reviews for these additions to the code.

Test cases to come.
For now implementation is without a UI but allows for user input still.

### CODE REVIEW

**Comment by turne142** [comment]
Here is the code for my workouts page UI, so it can help you as a reference. 


public class WorkoutsPage {

    WorkoutsPage() {

        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(320, 564);
        frame.setLayout(null);
        frame.setTitle("Routine Manager");

        JPanel workouts = new JPanel();
        workouts.setLocation(0, 250);
        workouts.setBounds(50, 144, 200, 275);
        workouts.setBackground(Color.lightGray);
        workouts.setLayout(new FlowLayout(FlowLayout.CENTER));

        JButton workout1 = new JButton();
        JButton workout2 = new JButton();
        JButton workout3 = new JButton();
        JButton workout4 = new JButton();
        JButton workout5 = new JButton();
        workout1.setText("Workout 1");
        workout2.setText("Workout 2");
        workout3.setText("Workout 3");
        workout4.setText("Workout 4");
        workout5.setText("Workout 5");
        workout1.setFocusable(false);
        workout2.setFocusable(false);
        workout3.setFocusable(false);
        workout4.setFocusable(false);
        workout5.setFocusable(false);
        workout1.setFont(new Font("Dialog", Font.BOLD, 30));
        workout2.setFont(new Font("Dialog", Font.BOLD, 30));
        workout3.setFont(new Font("Dialog", Font.BOLD, 30));
        workout4.setFont(new Font("Dialog", Font.BOLD, 30));
        workout5.setFont(new Font("Dialog", Font.BOLD, 30));

        workouts.add(workout1);
        workouts.add(workout2);
        workouts.add(workout3);
        workouts.add(workout4);
        workouts.add(workout5);

        frame.add(workouts);
        frame.setVisible(true);

        ActionListener a = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (e.getSource() == workout1) {
                    System.exit(0);
                }
                if (e.getSource() == workout2) {
                    System.out.println("You selected Workout 2");
                }
                if (e.getSource() == workout3) {
                    System.exit(0);
                }
                if (e.getSource() == workout4) {
                    System.exit(0);
                }
                if (e.getSource() == workout5) {
                    System.exit(0);
                }
            }
        };

        workout1.addActionListener(a);
        workout2.addActionListener(a);
        workout3.addActionListener(a);
        workout4.addActionListener(a);
        workout5.addActionListener(a);
    }
}

**Comment by bdls-jamal** [comment]
Need to incorporate the USER entity rather than changing the database based on user input alone. Currently the code for certain cases will run into errors when a user shares information with another user. Example: changing the password will change the SQL database information based on user input of their old password. If this old password is the same as another user's password it will also change that other user's password. This is not the intended functionality but can only be changed when the USER entity is incorporated.

**Comment by bdls-jamal** [comment]
Merging without reviews so that the TA can run this feature. Reviews will be done at a later date.

**Review by ghost — COMMENTED** [review]
General Clean Architecture is followed, 
Really Liked how the feature is organized into different layers on clean architecture, like the controllers, setting use cases,  and different view models based on the use cases, such as the password View if you click the change password button.
In terms of Solid Principle, the classes are structured in a way that is open for extension, but closed for modifications.

**Comment by bdls-jamal** [comment]
Command behavioural pattern is used as we objectify various SQL queries in a separate class DataManager which are then executed by a different class DashboardController. This demonstrates the design structure and allows for flexibility with timing of execution.

**Comment by bdls-jamal** [comment]
There is also use of the facade design pattern as the DashboardController calls upon various other classes and divides up the work while not implementing any functionality itself.

**Pull request merged**
