### PR TITLE
4 feature 6 workout data analysis

### PR DESCRIPTION
**Pull request by tejcapildeo**
Inverted the dependency of the presenter on the view. 3 of the 4 buttons are completely functional. All that's left to do now is to make the target screen, and also to do testing on everything.

### CODE REVIEW

**Review by bdls-jamal — DISMISSED** [review]
Class and variable names follow coherent code styling with the rest of the group. 

Potential code smell: large amounts of code that may or may not be able to be simplified into a separate class to manage various cases for duplicate code.

All in all the code is very readable and easy to follow. Variable names make sense.

**Comment by absolute-xero7** [comment]
The code is easy to follow and makes good use of JavaDoc.

A few classes can be considered too complex, possibility of making simpler classes.

Class and variable names follow convention.

**Comment by tejcapildeo** [comment]
Now the feature is entirely functional. The only missing link in the program is where the graphing feature gets its data from. Apart from that, it all works. Javadoc has been added, and clean architecture was followed as closely as possible.

**Comment by tejcapildeo** [comment]
More information about the SOLID principles used and the design patterns used are in the Milestone 5 document that will be linked.

**Pull request merged**
